services:
  app:
    image: ghcr.io/marcuwynu23/express-typescript-sample:latest
    ports:
      - "5000:5000"
    environment:
      OPENTELEMETRY_URL: http://otel-collector:4317
    networks:
      - monitoring

  # Collects traces and exports span metrics for Prometheus
  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    container_name: otel-collector
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./opentelemetry/otel-config.yaml:/etc/otel-collector-config.yaml:Z
    ports:
      - "4317:4317" # OTLP gRPC (Your app sends traces here)
      - "8889:8889" # Prometheus scrapes here
    networks:
      - monitoring

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    environment:
      - METRICS_STORAGE_TYPE=prometheus
      - PROMETHEUS_SERVER_URL=http://prometheus:9090
      - PROMETHEUS_QUERY_SUPPORT_SPANMETRICS_CONNECTOR=true
    ports:
      - "16686:16686"
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus/prometheus.yaml:/etc/prometheus/prometheus.yml:Z
    ports:
      - "9090:9090" # Access Prometheus directly on this port
    networks:
      - monitoring

networks:
  monitoring:
    driver: bridge