server:
    # Listen on all interfaces inside the container
    interface: 0.0.0.0
    port: 53

    # Allow your hotspot network
    access-control: 10.126.90.0/24 allow

    # Local DNS zone
    local-zone: "marcuwynu23.local." static

    # Local DNS records
    local-data: "dns.marcuwynu23.local. IN A 10.126.90.210"
    local-data: "gateway.marcuwynu23.local. IN A 10.126.90.124"

    local-data: "vm01.marcuwynu23.local. IN A 10.126.90.101"
    local-data: "vm02.marcuwynu23.local. IN A 10.126.90.102"
    local-data: "vm03.marcuwynu23.local. IN A 10.126.90.103"

    # Security / privacy
    hide-identity: yes
    hide-version: yes

    # DNSSEC
    harden-dnssec-stripped: yes

    # Cache
    cache-min-ttl: 60
    cache-max-ttl: 86400

    # Logging
    verbosity: 1


# Forward external DNS queries
forward-zone:
    name: "."
    forward-addr: 10.126.90.124
    forward-addr: 1.1.1.1
    forward-addr: 8.8.8.8