services:
  apprise:
    image: caronc/apprise:latest
    container_name: apprise
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      APPRISE_STATEFUL_MODE: simple
    volumes:
      - ./config/apprise.yml:/config/apprise.yml
