options {
    directory "/var/cache/bind";

    listen-on {
        any;
    };

    listen-on-v6 {
        any;
    };

    allow-query {
        10.126.90.0/24;
        localhost;
    };

    recursion yes;

    forwarders {
        10.126.90.124;
        1.1.1.1;
        8.8.8.8;
    };

    dnssec-validation auto;
};

zone "marcuwynu23.local" {
    type master;
    file "/etc/bind/zones/db.marcuwynu23.local";
};