services:
  plane-db:
    image: postgres:15
    container_name: plane-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: plane
      POSTGRES_USER: plane
      POSTGRES_PASSWORD: plane
    volumes:
      - plane-db:/var/lib/postgresql/data

  plane-redis:
    image: redis:7
    container_name: plane-redis
    restart: unless-stopped
    volumes:
      - plane-redis:/data

  plane-api:
    image: makeplane/plane-backend:latest
    container_name: plane-api
    restart: unless-stopped
    depends_on:
      - plane-db
      - plane-redis
    command: >
      sh -c "python manage.py migrate &&
             gunicorn plane.wsgi:application --bind 0.0.0.0:8000"
    environment:
      DATABASE_URL: postgres://plane:plane@plane-db:5432/plane
      REDIS_URL: redis://plane-redis:6379/0

      CELERY_BROKER_URL: redis://plane-redis:6379/0
      CELERY_RESULT_BACKEND: redis://plane-redis:6379/0

      SECRET_KEY: "0277a55224f54199c7024b1786b5a305ac0bc887deda8d4bb1fdf0b0a257e9308c76d45e12443f6251fa0638f28e6523807c1cee009adb7510f76a7215022a25"

      DEBUG: "0"
      ALLOWED_HOSTS: "*"

    ports:
      - "8000:8000"

  plane-worker:
    image: makeplane/plane-backend:latest
    container_name: plane-worker
    restart: unless-stopped
    depends_on:
      - plane-api
    command: celery -A plane worker -l info 
    environment:
      DATABASE_URL: postgres://plane:plane@plane-db:5432/plane
      REDIS_URL: redis://plane-redis:6379/0

      CELERY_BROKER_URL: redis://plane-redis:6379/0
      CELERY_RESULT_BACKEND: redis://plane-redis:6379/0

      SECRET_KEY: "0277a55224f54199c7024b1786b5a305ac0bc887deda8d4bb1fdf0b0a257e9308c76d45e12443f6251fa0638f28e6523807c1cee009adb7510f76a7215022a25"

  plane-web:
    image: makeplane/plane-frontend:latest
    container_name: plane-web
    restart: unless-stopped
    depends_on:
      - plane-api
    ports:
      - "8080:3000"
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8000
      NEXT_PUBLIC_APP_URL: http://localhost:8080

volumes:
  plane-db:
  plane-redis:
