services:
  bind9:
    image: ubuntu/bind9:latest
    container_name: bind9
    restart: unless-stopped

    ports:
      - "53:53/tcp"
      - "53:53/udp"

    volumes:
      - ./config/named.conf:/etc/bind/named.conf:ro
      - ./config/zones:/etc/bind/zones:ro
