global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  # Scrape Kubernetes Node Metrics
  - job_name: "kubernetes-nodes"
    scheme: https
    metrics_path: /metrics
    static_configs:
      - targets:
          - 192.168.1.118:10250   # master or node IPs
          - 192.168.1.142:10250
          - 192.168.1.143:10250
          - 192.168.1.144:10250
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /etc/prometheus/token.txt

  # Scrape cAdvisor Metrics
  - job_name: "cadvisor"
    scheme: https
    metrics_path: /metrics/cadvisor
    static_configs:
      - targets:
          - 192.168.1.118:10250
          - 192.168.1.142:10250
          - 192.168.1.143:10250
          - 192.168.1.144:10250
    tls_config:
      insecure_skip_verify: true
    bearer_token_file: /etc/prometheus/token.txt
