services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./data/storage:/qdrant/storage
      - ./data/snapshots:/qdrant/snapshots
