services:
  couchdb:
    image: couchdb:latest
    container_name: couchdb
    restart: unless-stopped
    ports:
      - "5984:5984"
    environment:                 # <--- Corrected from 'environments'
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    volumes:
      - couchdb-data:/opt/couchdb/data

volumes:
  couchdb-data: