services:
  snyk:
    image: snyk/snyk:docker
    working_dir: /app
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SNYK_TOKEN=${SNY_TOKEN}
    entrypoint: ["snyk"]
