services:
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:lts
    restart: always
    command: --http-enabled
    volumes:
      # Docker default:
      #   PORTAINER_SOCKET=/var/run/docker.sock
      # Podman example:
      #   PORTAINER_SOCKET=/var/run/podman/podman.sock
      - ${PORTAINER_SOCKET:-/var/run/docker.sock}:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9000:9000"
      - "8000:8000"  # Remove if you do not intend to use Edge Agents

volumes:
  portainer_data:
    name: portainer_data

networks:
  default:
    name: portainer_network